# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tservicepb\" \n\x0fResearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"H\n\x10ResearchResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x11\n\tresources\x18\x02 \x03(\t\x12\x10\n\x08\x63ritique\x18\x03 \x01(\t2V\n\x0fResearchService\x12\x43\n\x08Research\x12\x1a.servicepb.ResearchRequest\x1a\x1b.servicepb.ResearchResponseB9Z7github.com/ManoVikram/AI-Research-Assistant/backend/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/ManoVikram/AI-Research-Assistant/backend/api'
  _globals['_RESEARCHREQUEST']._serialized_start=28
  _globals['_RESEARCHREQUEST']._serialized_end=60
  _globals['_RESEARCHRESPONSE']._serialized_start=62
  _globals['_RESEARCHRESPONSE']._serialized_end=134
  _globals['_RESEARCHSERVICE']._serialized_start=136
  _globals['_RESEARCHSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
