// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchRequest) Reset() {
	*x = ResearchRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchRequest) ProtoMessage() {}

func (x *ResearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchRequest.ProtoReflect.Descriptor instead.
func (*ResearchRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Resources     []string               `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Critique      string                 `protobuf:"bytes,3,opt,name=critique,proto3" json:"critique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchResponse) Reset() {
	*x = ResearchResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchResponse) ProtoMessage() {}

func (x *ResearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchResponse.ProtoReflect.Descriptor instead.
func (*ResearchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResearchResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResearchResponse) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ResearchResponse) GetCritique() string {
	if x != nil {
		return x.Critique
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tservicepb\"'\n" +
	"\x0fResearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"f\n" +
	"\x10ResearchResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1c\n" +
	"\tresources\x18\x02 \x03(\tR\tresources\x12\x1a\n" +
	"\bcritique\x18\x03 \x01(\tR\bcritique2V\n" +
	"\x0fResearchService\x12C\n" +
	"\bResearch\x12\x1a.servicepb.ResearchRequest\x1a\x1b.servicepb.ResearchResponseB9Z7github.com/ManoVikram/AI-Research-Assistant/backend/apib\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(*ResearchRequest)(nil),  // 0: servicepb.ResearchRequest
	(*ResearchResponse)(nil), // 1: servicepb.ResearchResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: servicepb.ResearchService.Research:input_type -> servicepb.ResearchRequest
	1, // 1: servicepb.ResearchService.Research:output_type -> servicepb.ResearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
