// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResearchService_Research_FullMethodName = "/servicepb.ResearchService/Research"
)

// ResearchServiceClient is the client API for ResearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResearchServiceClient interface {
	Research(ctx context.Context, in *ResearchRequest, opts ...grpc.CallOption) (*ResearchResponse, error)
}

type researchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResearchServiceClient(cc grpc.ClientConnInterface) ResearchServiceClient {
	return &researchServiceClient{cc}
}

func (c *researchServiceClient) Research(ctx context.Context, in *ResearchRequest, opts ...grpc.CallOption) (*ResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResearchResponse)
	err := c.cc.Invoke(ctx, ResearchService_Research_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResearchServiceServer is the server API for ResearchService service.
// All implementations must embed UnimplementedResearchServiceServer
// for forward compatibility.
type ResearchServiceServer interface {
	Research(context.Context, *ResearchRequest) (*ResearchResponse, error)
	mustEmbedUnimplementedResearchServiceServer()
}

// UnimplementedResearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResearchServiceServer struct{}

func (UnimplementedResearchServiceServer) Research(context.Context, *ResearchRequest) (*ResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Research not implemented")
}
func (UnimplementedResearchServiceServer) mustEmbedUnimplementedResearchServiceServer() {}
func (UnimplementedResearchServiceServer) testEmbeddedByValue()                         {}

// UnsafeResearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResearchServiceServer will
// result in compilation errors.
type UnsafeResearchServiceServer interface {
	mustEmbedUnimplementedResearchServiceServer()
}

func RegisterResearchServiceServer(s grpc.ServiceRegistrar, srv ResearchServiceServer) {
	// If the following call panics, it indicates UnimplementedResearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResearchService_ServiceDesc, srv)
}

func _ResearchService_Research_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchServiceServer).Research(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchService_Research_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchServiceServer).Research(ctx, req.(*ResearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResearchService_ServiceDesc is the grpc.ServiceDesc for ResearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.ResearchService",
	HandlerType: (*ResearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Research",
			Handler:    _ResearchService_Research_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
